Alterações Jessica
Vacina-Pet/vacina-pet-front pull request #21
Opened 2023-05-24 03:10 UTC by jessic4neves

Solicito o merge das minhas alterações.

2023-05-24 22:29 UTC, jersonb commented on pet/pet-create.html
> +        <input class="input-text" type="text" name="" id="data-nasc" placeholder="dia/mês/ano">
utilizar input type dade

2023-05-24 22:35 UTC, jersonb requested changes
favor revisar comentários

2023-05-24 22:35 UTC, jersonb commented on pet/pet-create.html
> +       <div class="foto">
adicionar input file image

2023-05-24 22:35 UTC, jersonb commented on pet/pet-create.html
>  </head>
adicionar chamada da pagina de criação ao botão novo pet na pagina home (index)

2023-05-26 02:13 UTC, jessic4neves commented on pet/pet-create.html
>  </head>
feito!

2023-05-26 02:18 UTC, jessic4neves commented on pet/pet-create.html
> +        <input class="input-text" type="text" name="" id="data-nasc" placeholder="dia/mês/ano">
feito!

2023-05-26 19:34 UTC, jersonb approved these changes

2023-05-26 19:35 UTC, merged